# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
# Сервис метрик из Docker контейнеров
    cadvisor-exporter:
        container_name: "cadvisor-exporter"
        image: gcr.io/cadvisor/cadvisor
        ports:
            - 8080:8080
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        restart: always
#Сервис сбора метрик MySQL
    mysql-exporter:
        image: prom/mysqld-exporter
        container_name: mysql-exporter
        restart: always
        environment:
        - DATA_SOURCE_NAME=${MYSQL_USER_EXPORTER}:${MYSQL_PASSWORD_EXPORTER}@(mysql:3306)/
        ports:
            - 9104:9104
    